---
- name: Taking Backup before Patching
  hosts: ubuntu
  remote_user: ubuntu
  become: true

  tasks:
    -
      name: Create a backup directory
      file:
        path: /backup
        state: directory

    - name: Backup system files to tarball
      synchronize:
        src: /
        dest: /backup/system_backup
        rsync_opts: '--exclude=/proc --exclude=/sys --exclude=/dev'
        mode: '0644'

    - name: Backup package list
      shell:
        cmd: dpkg --get-selections > /backup/package_list.txt

    - name: Backup configuration files
      shell:
        cmd: getconf -a > /backup/config_files.txt