---
- name: Patch Ubuntu OS
  hosts: ubuntu
  remote_user: ubuntu
  become: true

  
  pre_tasks:
    - name: Add host key to known_hosts
      shell: |
        ssh-keyscan -H {{ hostvars[inventory_hostname]['ansible_host'] }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      become: no

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: full

    - name: Install security updates
      apt:
        name: "*"
        state: latest
        autoremove: yes
    

   
    - name: Apply security patches for RVM-managed Ruby versions
      shell: |
        source /home/ubuntu/.rvm/scripts/rvm
        rvm get stable --auto-dotfiles
        rvm all do gem update --system --force
      args:
        executable: /bin/bash
      become: yes
      tags: rvm_security_patches


   

    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//      "${distro_id}:${distro_codename}-security";'
        line: '      "${distro_id}:${distro_codename}-security";'
        state: present
        create: yes

    - name: Enable automatic security updates
      lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: '^APT::Periodic::Update-Package-Lists'
        line: 'APT::Periodic::Update-Package-Lists "1";'
        state: present
        create: yes

    - name: Enable Ubuntu's Security Repository
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32
        state: present

    - name: Install OpenSSH Server with latest security patches
      apt:
        name: openssh-server
        state: latest

    - name: Install OpenSSL with latest security patches
      apt:
        name: openssl
        state: latest

    - name: Install Linux Kernel with latest security patches
      apt:
        name: linux-generic
        state: latest

    


    - name: Run ubuntu-security-status to check for vulnerable packages
      command: ubuntu-security-status
      register: ubuntu_security_status

    - name: Install debsecan package
      apt:
        name: debsecan  
        state: present

    - name: Run debsecan to scan for vulnerable packages
      command: debsecan
      register: debsecan_result


   

    - name: Trigger email notification
      meta: flush_handlers

  handlers:
    - name: Send test email
      shell: |
        echo -e "To: lakshmi.narayana@bluebash.co\nSubject: Ansible Playbook Execution - SUCCESS\n\nThe Ansible playbook has been successfully executed." | /usr/bin/msmtp --debug --account=gmail lakshmi.narayana@bluebash.co
      delegate_to: localhost