---
- name: Roll Back to Previous kernel
  hosts: ubuntu
  remote_user: ubuntu
  become: true

  tasks:
    - name: Get list of installed kernel versions
      shell: dpkg -l | grep linux-image | awk '{print $2}'
      register: kernel_versions

    - name: Get current kernel version
      shell: uname -r
      register: current_kernel_version

    - name: Find previous kernel version
      set_fact:
        previous_kernel_version: "{{ kernel_versions.stdout_lines | select('ne', current_kernel_version.stdout) | last }}"

    - name: Rollback to previous kernel version
      apt:
        name: "{{ previous_kernel_version }}"
        state: present