---
- name: Patch Ubuntu OS
  hosts: ubuntu
  remote_user: ubuntu
  become: true

  pre_tasks:
    - name: Add host key to known_hosts
      shell: ssh-keyscan -t rsa {{ hostvars[inventory_hostname]['ansible_host'] }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      become: no
      loop: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | list }}"

  tasks:
    - name: Check if application is running
      shell:
        cmd: "pgrep -f nginx || pgrep -f redis || true"
      register: app_running

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Upgrade kernel to latest version
      apt:
        name: linux-generic
        state: latest

    - name: Install security updates
      apt:
        name: "*"
        state: latest
        autoremove: yes

    - name: Dist-upgrade
      apt:
        upgrade: full

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Autoremove unused packages
      apt:
        autoremove: yes

    - name: Autoclean package cache
      apt:
        autoclean: yes

    - name: Install and configure unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable unattended-upgrades
      lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//      "${distro_id}:${distro_codename}-security";'
        line: '      "${distro_id}:${distro_codename}-security";'
        state: present

    - name: Enable automatic security updates
      lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: '^APT::Periodic::Update-Package-Lists'
        line: 'APT::Periodic::Update-Package-Lists "1";'
        state: present

    - name: Enable automatic security upgrades
      lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: '^APT::Periodic::Unattended-Upgrade'
        line: 'APT::Periodic::Unattended-Upgrade "1";'
        state: present

    - name: Enable Ubuntu's Security Repository
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32
        state: present

    - name: Install OpenSSH Server with latest security patches
      apt:
        name: openssh-server
        state: latest

    - name: Install OpenSSL with latest security patches
      apt:
        name: openssl
        state: latest

    - name: Install Linux Kernel with latest security patches
      apt:
        name: linux-generic
        state: latest

    - name: Install update-manager-core package
      apt:
        name: update-manager-core
        state: present

    - name: Run ubuntu-security-status to check for vulnerable packages
      command: ubuntu-security-status
      register: ubuntu_security_status

    - name: Install debsecan package
      apt:
        name: debsecan
        state: present

    - name: Run debsecan to scan for vulnerable packages
      command: debsecan
      register: debsecan_result

    - name: Install Certbot's Nginx plugin
      apt:
        name: python3-certbot-nginx
        state: present

    - name: Configure Certbot to renew certificates automatically
      cron:
        name: certbot renew
        minute: 0
        hour: 0
        day: "*"
        month: "*"
        weekday: "*"
        job: certbot renew

    - name: Install Ubuntu Advantage Tools for Livepatch
      apt:
        name: ubuntu-advantage-tools
        state: latest

    - name: Install apt-listchanges
      apt:
        name: apt-listchanges
        state: present

    - name: Trigger email notification
      meta: flush_handlers
    
    - meta: end_play

  handlers:
    - name: Send test email
      shell: |
        echo -e "To: lakshmi.narayana@bluebash.co\nSubject: Ansible Playbook Execution - SUCCESS\n\nThe Ansible playbook has been successfully executed." | /usr/bin/msmtp --debug --account=gmail lakshmi.narayana@bluebash.co
      delegate_to: localhost